
INSERT INTO usuarios (nombre_completo, email, contrasena, tipo_usuario, foto_perfil, fecha_registro, activo) VALUES
('Gorka Ramirez',          'gorkaramirez@runandeat.com',          '123', 'organizador', 'public/img/user-photos/user.png', NOW(), 1),
('Ignacio Breñas',         'ignaciobrenas@runandeat.com',         '123', 'organizador', 'public/img/user-photos/user.png', NOW(), 1),
('Ian Gamo',               'iangamo@runandeat.com',               '123', 'cliente',     'public/img/user-photos/user.png', NOW(), 1),
('Jose Manuel Rodriguez',  'josemanuelrodriguez@runandeat.com',   '123', 'cliente',     'public/img/user-photos/user.png', NOW(), 1);


-- ============================================================
-- INSERT EVENTOS (10 eventos de ejemplo)
-- Organizadores: 1 = Gorka Ramirez | 2 = Ignacio Breñas
-- Categorías: ver tabla CATEGORIAS
-- ============================================================

INSERT INTO EVENTOS (id_organizador, id_categoria, titulo, descripcion, imagen, fecha, hora, ciudad, pais, direccion_completa, precio, capacidad, plazas_disponibles, distancia, nivel, que_incluye, que_traer, notas_adicionales, valoracion_promedio, total_valoraciones) VALUES

(1,  1,  'Cata de Vinos de La Rioja',
 'Descubre los mejores vinos de La Rioja de la mano de un sumiller experto. Degustaremos 6 variedades diferentes acompañadas de tabla de quesos y embutidos ibéricos.',
 'public/img/eventos-photos/cata-vinos-rioja.jpg',
 '2026-07-15', '19:00:00', 'Logroño', 'España',
 'Calle Laurel 12, Logroño, La Rioja',
 35.00, 20, 20, NULL, 'Todos los niveles',
 'Degustación de 6 vinos, tabla de quesos y embutidos, guía de cata',
 'Ganas de aprender y disfrutar',
 'Evento para mayores de 18 años',
 2.75, 87),

(2,  2,  'Festival de Hamburguesas Artesanales',
 'Una tarde de celebración de la mejor hamburguesa artesanal de Madrid. Participarán 5 chefs locales con sus recetas únicas. Votarás tu favorita.',
 'public/img/eventos-photos/festival-hamburguesas.jpg',
 '2026-07-22', '13:00:00', 'Madrid', 'España',
 'Mercado de San Fernando, Calle Embajadores 41, Madrid',
 20.00, 50, 50, NULL, 'Todos los niveles',
 '5 hamburguesas artesanales, bebida incluida, postre',
 'Buen apetito',
 'Opción sin gluten disponible bajo petición',
 3.90, 62),

(1,  4,  'Ruta de Tapas por el Barrio Gótico',
 'Recorre los mejores bares de tapas del Barrio Gótico de Barcelona con guía local. Visitaremos 5 locales emblemáticos con tapa y bebida incluida en cada parada.',
 'public/img/eventos-photos/ruta-tapas-gotico.jpg',
 '2026-08-01', '19:30:00', 'Barcelona', 'España',
 'Punt de trobada: Plaça de Sant Jaume, Barcelona',
 28.00, 15, 15, 4.00, 'Fácil',
 '5 tapas en diferentes locales, 5 bebidas, guía local',
 'Calzado cómodo',
 'La ruta dura aproximadamente 2 horas y media',
 3.50, 41),

(2,  13, 'Noche de Sushi Omakase',
 'Vive la experiencia del menú omakase japonés: el chef decide los mejores bocados del día. Incluye 12 piezas de sushi premium, miso y té verde.',
 'public/img/eventos-photos/sushi-omakase.jpg',
 '2026-08-10', '20:30:00', 'Barcelona', 'España',
 'Carrer del Parlament 24, Barcelona',
 55.00, 12, 12, NULL, 'Todos los niveles',
 '12 piezas de sushi omakase, sopa de miso, té verde, postre mochi',
 'Curiosidad por la gastronomía japonesa',
 'Informar de alergias al marisco con antelación',
 4.85, 33),

(1,  12, 'Taller de Pizza Napolitana Auténtica',
 'Aprende de la mano de un pizzero napolitano a preparar la auténtica pizza italiana: desde la masa madre hasta el horneado en horno de leña. Te llevas tu pizza.',
 'public/img/eventos-photos/taller-pizza-napolitana.jpg',
 '2026-08-18', '17:00:00', 'Valencia', 'España',
 'Calle del Mar 45, Valencia',
 30.00, 16, 16, NULL, 'Principiante',
 'Ingredientes, delantal, receta impresa, pizza para llevar a casa',
 'Ropa cómoda que no te importe manchar',
 'Niños mayores de 10 años pueden participar acompañados',
 2.20, 55),

(2,  14, 'Ruta Gastronómica de Tacos Mexicanos',
 'Sumérgete en la auténtica gastronomía mexicana recorriendo los mejores restaurantes mexicanos de Madrid. Descubrirás la diferencia entre los distintos tipos de tacos.',
 'public/img/eventos-photos/ruta-tacos-mexicanos.jpg',
 '2026-09-05', '14:00:00', 'Madrid', 'España',
 'Punto de encuentro: Puerta del Sol, Madrid',
 25.00, 20, 20, 3.50, 'Fácil',
 '4 degustaciones de tacos, bebida en cada parada, guía experto en cocina mexicana',
 'Calzado cómodo y buen apetito',
 'La ruta dura aproximadamente 2 horas',
 3.70, 78),

(1,  10, 'Experiencia de Curry Indio con Chef Local',
 'Un viaje de sabores a la India sin salir de Sevilla. El chef Raj nos guiará en una degustación de 5 currys con distintos niveles de picante, acompañados de naan y arroz basmati.',
 'public/img/eventos-photos/curry-indio-sevilla.jpg',
 '2026-09-12', '20:00:00', 'Sevilla', 'España',
 'Calle Feria 89, Sevilla',
 32.00, 25, 25, NULL, 'Todos los niveles',
 '5 variedades de curry, pan naan, arroz basmati, lassi de bienvenida',
 'Afición por los sabores especiados',
 'Indica tu nivel de tolerancia al picante al inscribirte',
 4.60, 47),

(2,  15, 'Brunch Vegano en el Parque del Retiro',
 'Un brunch saludable y sostenible en plena naturaleza. Disfrutaremos de un menú 100% vegetal de temporada elaborado con ingredientes locales y de kilómetro cero.',
 'public/img/eventos-photos/brunch-vegano.jpg',
 '2026-09-20', '10:30:00', 'Madrid', 'España',
 'Parque del Retiro, entrada Puerta de Alcalá, Madrid',
 22.00, 30, 30, NULL, 'Todos los niveles',
 'Brunch vegano completo, zumos naturales, café o té, manta para sentarse',
 'Ganas de descubrir la cocina vegana',
 'Evento al aire libre. En caso de lluvia se pospondrá',
 4.10, 29),

(1,  9,  'Noche de Ramen Japonés',
 'Descubre los secretos del ramen auténtico japonés. Un chef especializado preparará en directo tres variedades: Tonkotsu, Shoyu y Miso. Aprenderás a prepararlo en casa.',
 'public/img/eventos-photos/noche-ramen.jpg',
 '2026-10-08', '19:00:00', 'Barcelona', 'España',
 'Carrer de Blai 30, Barcelona',
 38.00, 18, 18, NULL, 'Todos los niveles',
 'Degustación de 3 variedades de ramen, gyozas de bienvenida, receta para llevar, sake de bienvenida',
 'Curiosidad por la cocina japonesa',
 'Apto para vegetarianos indicando preferencia al inscribirse',
 4.95, 64),

(2,  8,  'Cena Italiana en Trattoria Familiar',
 'Una auténtica experiencia culinaria italiana en una trattoria familiar. Menú de 4 platos elaborados con recetas tradicionales italianas transmitidas de generación en generación.',
 'public/img/eventos-photos/trattoria-italiana.jpg',
 '2026-10-17', '21:00:00', 'Madrid', 'España',
 'Calle Ponzano 12, Madrid',
 45.00, 22, 22, NULL, 'Todos los niveles',
 'Menú de 4 platos (antipasto, primo, secondo, dolce), copa de vino, agua y café',
 'Apetito y ganas de vivir Italia en Madrid',
 'Menú sin gluten disponible con 48h de antelación',
 4.40, 91);
